export type AdminResource = {
  key: string;
  label: string;
  path: string; // matches backend route
  primaryKeys: string[];
  columns: string[]; // fields to render in list/table
  allowedFields?: string[]; // hints for form JSON
  fieldEnums?: Record<string, string[]>; // enum options per field
};

export const adminResources: AdminResource[] = [
  {
    key: "users",
    label: "Users",
    path: "users",
    primaryKeys: ["id"],
    columns: ["email", "role", "isVerified", "isActive", "createdAt"],
    allowedFields: [
      "email",
      "passwordHash",
      "firstName",
      "lastName",
      "phone",
      "avatarUrl",
      "role",
      "isVerified",
      "isActive",
      "lastLoginAt",
    ],
    fieldEnums: {
      role: ["ADMIN", "CANDIDATE", "RECRUITER"],
    },
  },
  {
    key: "companies",
    label: "Companies",
    path: "companies",
    primaryKeys: ["id"],
    columns: ["name", "logoUrl", "coverUrl", "slug", "industry", "companySize", "city", "country", "isVerified"],
    allowedFields: [
      "name",
      "slug",
      "logoUrl",
      "coverUrl",
      "website",
      "description",
      "industry",
      "companySize",
      "foundedYear",
      "address",
      "city",
      "country",
      "isVerified",
    ],
  },
  {
    key: "jobs",
    label: "Jobs",
    path: "jobs",
    primaryKeys: ["id"],
    columns: ["title", "companyId", "type", "status", "skills", "categories", "location", "isRemote", "salaryMin", "salaryMax", "currency"],
    allowedFields: [
      "slug",
      "title",
      "companyId",
      "recruiterId",
      "description",
      "requirements",
      "benefits",
      "type",
      "status",
      "location",
      "isRemote",
      "salaryMin",
      "salaryMax",
      "currency",
      "isSalaryNegotiable",
      "experienceLevel",
      "quantity",
      "viewsCount",
      "clicksCount",
      "publishedAt",
      "deadline",
    ],
    fieldEnums: {
      type: ["FULL_TIME", "PART_TIME", "CONTRACT", "FREELANCE", "INTERNSHIP", "REMOTE"],
      status: ["DRAFT", "PUBLISHED", "ARCHIVED", "CLOSED"],
      currency: ["VND", "USD", "EUR", "JPY"],
    },
  },
  {
    key: "skills",
    label: "Skills",
    path: "skills",
    primaryKeys: ["id"],
    columns: ["name", "iconUrl"],
    allowedFields: ["name", "iconUrl"],
  },
  {
    key: "categories",
    label: "Categories",
    path: "categories",
    primaryKeys: ["id"],
    columns: ["name", "iconUrl"],
    allowedFields: ["name", "iconUrl"],
  },
  {
    key: "applications",
    label: "Applications",
    path: "applications",
    primaryKeys: ["id"],
    columns: ["jobId", "candidateId", "status", "appliedAt"],
    allowedFields: [
      "jobId",
      "candidateId",
      "resumeUrl",
      "coverLetter",
      "status",
      "rejectionReason",
    ],
    fieldEnums: {
      status: ["APPLIED", "REVIEWING", "SHORTLISTED", "INTERVIEW_SCHEDULED", "INTERVIEWED", "OFFER_SENT", "HIRED", "REJECTED", "WITHDRAWN"],
    },
  },
  {
    key: "interviews",
    label: "Interviews",
    path: "interviews",
    primaryKeys: ["id"],
    columns: ["title", "applicationId", "type", "status", "accessCode", "expiresAt"],
    allowedFields: [
      "applicationId",
      "title",
      "type",
      "status",
      "accessCode",
      "sessionUrl",
      "expiresAt",
      "startedAt",
      "endedAt",
      "durationSeconds",
      "overallScore",
      "summary",
      "recommendation",
      "recordingUrl",
      "fullTranscript",
      "aiAnalysisData",
    ],
    fieldEnums: {
      type: ["AI_VIDEO", "AI_VOICE", "AI_CHAT", "CODING_TEST"],
      status: ["PENDING", "IN_PROGRESS", "PROCESSING", "COMPLETED", "FAILED", "EXPIRED"],
    },
  },
  {
    key: "messages",
    label: "Messages",
    path: "messages",
    primaryKeys: ["id"],
    columns: ["senderId", "receiverId", "jobId", "applicationId", "isRead", "createdAt"],
    allowedFields: ["senderId", "receiverId", "content", "isRead", "jobId", "applicationId"],
  },
  {
    key: "notifications",
    label: "Notifications",
    path: "notifications",
    primaryKeys: ["id"],
    columns: ["userId", "title", "type", "isRead", "createdAt"],
    allowedFields: ["userId", "title", "message", "type", "isRead", "link"],
  },
];
