import type { CreateJobInput } from "./job.schema";

export const JobService = {
  async list() {
    return [
      {
        id: "11111111-1111-1111-1111-111111111111",
        title: "Senior Frontend Engineer",
        slug: "senior-frontend-engineer",
        company_id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        department_id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        employment_type: "FULL_TIME",
        work_model: "REMOTE",
        country: "Vietnam",
        city: "Ho Chi Minh",
        address: "123 Nguyen Van Linh, Thu Duc City",
        min_salary: 60000000,
        max_salary: 90000000,
        currency: "VND",
        experience_min_years: 4,
        experience_max_years: 8,
        job_level: "SENIOR",
        description: "We are looking for a Senior Frontend Engineer to join our team.",
        requirements:
          "- 4+ years working with modern frontend frameworks\n- Strong experience with React and TypeScript\n- Solid understanding of performance and accessibility",
        nice_to_have:
          "- Experience with design systems\n- Familiarity with Node.js or backend APIs\n- Experience working in product teams",
        responsibilities:
          "- Own core frontend experiences\n- Collaborate with Product & Design\n- Maintain a high-quality component library",
        skills: "React, TypeScript, Design Systems, Tailwind CSS",
      },
      {
        id: "22222222-2222-2222-2222-222222222222",
        title: "Mid-level Backend Engineer (Node.js)",
        slug: "backend-engineer-nodejs",
        company_id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        department_id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
        employment_type: "FULL_TIME",
        work_model: "HYBRID",
        country: "Vietnam",
        city: "Ha Noi",
        address: "25 Hai Ba Trung, Hoan Kiem",
        min_salary: 40000000,
        max_salary: 65000000,
        currency: "VND",
        experience_min_years: 3,
        experience_max_years: 6,
        job_level: "MID",
        description: "Build and scale backend services powering our core products.",
        requirements:
          "- 3+ years experience building APIs with Node.js\n- Solid understanding of relational databases (PostgreSQL/MySQL)\n- Experience with RESTful design",
        nice_to_have:
          "- Experience with microservices\n- Familiarity with message queues (Kafka, RabbitMQ)\n- Basic DevOps knowledge",
        responsibilities:
          "- Design, implement, and maintain backend services\n- Optimize database queries and performance\n- Work closely with frontend and product teams",
        skills: "Node.js, PostgreSQL, REST API, TypeScript",
      },
      {
        id: "33333333-3333-3333-3333-333333333333",
        title: "Junior Product Designer",
        slug: "junior-product-designer",
        company_id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
        department_id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
        employment_type: "FULL_TIME",
        work_model: "ON_SITE",
        country: "Vietnam",
        city: "Da Nang",
        address: "88 Vo Nguyen Giap, Son Tra",
        min_salary: 18000000,
        max_salary: 25000000,
        currency: "VND",
        experience_min_years: 1,
        experience_max_years: 3,
        job_level: "JUNIOR",
        description: "Work with senior designers to craft delightful user experiences.",
        requirements:
          "- 1+ years of experience or strong portfolio\n- Proficiency with Figma or similar tools\n- Basic understanding of UX research",
        nice_to_have:
          "- Motion design skills\n- Experience with design systems\n- Ability to prototype interactions",
        responsibilities:
          "- Collaborate with Product and Engineering\n- Create wireframes, flows, and hi-fi designs\n- Participate in design critiques and feedback loops",
        skills: "Figma, UX/UI, Prototyping, Design Systems",
      },
      {
        id: "44444444-4444-4444-4444-444444444444",
        title: "Senior Machine Learning Engineer",
        slug: "senior-ml-engineer",
        company_id: "ffffffff-ffff-ffff-ffff-ffffffffffff",
        department_id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
        employment_type: "FULL_TIME",
        work_model: "REMOTE",
        country: "Singapore",
        city: "Singapore",
        address: "1 Marina Boulevard",
        min_salary: 9000,
        max_salary: 14000,
        currency: "USD",
        experience_min_years: 5,
        experience_max_years: 10,
        job_level: "SENIOR",
        description: "Own ML systems from experimentation to production.",
        requirements:
          "- 5+ years working on ML/DS problems\n- Strong Python and ML frameworks (PyTorch/TensorFlow)\n- Experience deploying models to production",
        nice_to_have:
          "- Experience with LLMs\n- MLOps experience (Kubeflow, MLFlow, etc.)\n- Background in recommendation systems or search",
        responsibilities:
          "- Design and implement ML pipelines\n- Collaborate with product teams on ML features\n- Measure and iterate on model performance",
        skills: "Python, Machine Learning, MLOps, LLMs",
      },
      {
        id: "55555555-5555-5555-5555-555555555555",
        title: "Frontend Engineer (React Native)",
        slug: "frontend-engineer-react-native",
        company_id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        department_id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        employment_type: "CONTRACT",
        work_model: "REMOTE",
        country: "Vietnam",
        city: "Ho Chi Minh",
        address: "Remote",
        min_salary: 30000000,
        max_salary: 50000000,
        currency: "VND",
        experience_min_years: 2,
        experience_max_years: 5,
        job_level: "MID",
        description: "Help build and improve our mobile applications.",
        requirements:
          "- 2+ years with React Native\n- Familiarity with iOS and Android ecosystems\n- Experience consuming REST/GraphQL APIs",
        nice_to_have:
          "- Experience with native modules\n- Working knowledge of mobile CI/CD\n- App Store / Play Store releases",
        responsibilities:
          "- Implement new mobile features\n- Work closely with designers and backend engineers\n- Maintain app performance and stability",
        skills: "React Native, TypeScript, Mobile Development",
      },
      {
        id: "66666666-6666-6666-6666-666666666666",
        title: "Data Analyst",
        slug: "data-analyst",
        company_id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
        department_id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
        employment_type: "FULL_TIME",
        work_model: "HYBRID",
        country: "Vietnam",
        city: "Ho Chi Minh",
        address: "29 Nguyen Thi Minh Khai, District 1",
        min_salary: 25000000,
        max_salary: 40000000,
        currency: "VND",
        experience_min_years: 2,
        experience_max_years: 5,
        job_level: "MID",
        description: "Turn data into insights to drive product and business decisions.",
        requirements:
          "- 2+ years in data analytics\n- Strong SQL skills\n- Experience with BI tools (Tableau, Power BI, Metabase...)",
        nice_to_have:
          "- Basic Python/R for data analysis\n- Experience with A/B testing\n- Familiarity with event tracking tools",
        responsibilities:
          "- Build dashboards and reports\n- Work with stakeholders to define metrics\n- Analyze experiments and cohorts",
        skills: "SQL, BI Tools, Data Visualization",
      },
      {
        id: "77777777-7777-7777-7777-777777777777",
        title: "DevOps Engineer",
        slug: "devops-engineer",
        company_id: "ffffffff-ffff-ffff-ffff-ffffffffffff",
        department_id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        employment_type: "FULL_TIME",
        work_model: "HYBRID",
        country: "Vietnam",
        city: "Ha Noi",
        address: "12 Kim Ma, Ba Dinh",
        min_salary: 50000000,
        max_salary: 80000000,
        currency: "VND",
        experience_min_years: 3,
        experience_max_years: 7,
        job_level: "MID",
        description: "Build and maintain our cloud infrastructure.",
        requirements:
          "- 3+ years working with cloud providers (AWS/GCP/Azure)\n- Strong experience with CI/CD\n- Familiarity with containers and orchestration",
        nice_to_have:
          "- Terraform or similar IaC tools\n- Observability stack experience (Prometheus, Grafana, ELK)\n- Security best practices",
        responsibilities:
          "- Maintain and improve deployment pipelines\n- Ensure reliability and scalability of services\n- Collaborate with engineering teams on infrastructure needs",
        skills: "DevOps, Kubernetes, CI/CD, Terraform",
      },
      {
        id: "88888888-8888-8888-8888-888888888888",
        title: "Customer Success Manager",
        slug: "customer-success-manager",
        company_id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
        department_id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
        employment_type: "FULL_TIME",
        work_model: "ON_SITE",
        country: "Vietnam",
        city: "Ho Chi Minh",
        address: "60 Le Loi, District 1",
        min_salary: 25000000,
        max_salary: 35000000,
        currency: "VND",
        experience_min_years: 3,
        experience_max_years: 6,
        job_level: "MID",
        description: "Be the main point of contact to help our customers succeed.",
        requirements:
          "- 3+ years in customer-facing roles\n- Excellent communication skills\n- Experience working with SaaS products",
        nice_to_have:
          "- Experience with CRM tools\n- Background in product-led growth environments\n- Ability to run trainings and webinars",
        responsibilities:
          "- Onboard and support key customers\n- Gather feedback and work with Product\n- Monitor adoption and retention metrics",
        skills: "Customer Success, Communication, SaaS",
      },
      {
        id: "99999999-9999-9999-9999-999999999999",
        title: "HR Generalist",
        slug: "hr-generalist",
        company_id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        department_id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
        employment_type: "FULL_TIME",
        work_model: "ON_SITE",
        country: "Vietnam",
        city: "Ha Noi",
        address: "101 Tran Hung Dao, Hoan Kiem",
        min_salary: 20000000,
        max_salary: 30000000,
        currency: "VND",
        experience_min_years: 2,
        experience_max_years: 5,
        job_level: "MID",
        description: "Support HR operations across recruitment, onboarding, and culture.",
        requirements:
          "- 2+ years in HR roles\n- Knowledge of Vietnam labor law\n- Experience with recruitment processes",
        nice_to_have:
          "- Experience with HRIS tools\n- Employer branding experience\n- Organizing internal events",
        responsibilities:
          "- Manage recruitment pipeline\n- Support onboarding and offboarding\n- Help maintain company culture initiatives",
        skills: "HR, Recruitment, Communication",
      },
      {
        id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab",
        title: "Intern Software Engineer",
        slug: "intern-software-engineer",
        company_id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        department_id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        employment_type: "INTERN",
        work_model: "ON_SITE",
        country: "Vietnam",
        city: "Ho Chi Minh",
        address: "Campus, District 7",
        min_salary: 8000000,
        max_salary: 10000000,
        currency: "VND",
        experience_min_years: 0,
        experience_max_years: 1,
        job_level: "JUNIOR",
        description: "Start your career as a software engineer with mentorship and real projects.",
        requirements:
          "- Final-year student or fresh graduate in CS/IT or related fields\n- Basic knowledge of web development\n- Willingness to learn and take feedback",
        nice_to_have:
          "- Personal projects or GitHub profile\n- Experience with React or Node.js\n- Participation in tech clubs or competitions",
        responsibilities:
          "- Contribute to small features and bug fixes\n- Learn best practices from senior engineers\n- Participate in code reviews and team rituals",
        skills: "JavaScript, Web Development, Git",
      },
    ] as Array<CreateJobInput>;
  },
};


